class Autogenerated {
  bool? ok;
  String? message;
  List<Members>? members;

  Autogenerated({this.ok, this.message, this.members});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    ok = json['ok'];
    message = json['message'];
    if (json['members'] != null) {
      members = <Members>[];
      json['members'].forEach((v) {
        members!.add(Members.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['ok'] = ok;
    data['message'] = message;
    if (members != null) {
      data['members'] = members!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Members {
  String? chatId;
  String? userId;
  String? announcementId;
  String? createdAt;
  User? user;
  Post? post;
  Message? message;

  Members(
      {this.chatId,
        this.userId,
        this.announcementId,
        this.createdAt,
        this.user,
        this.post,
        this.message});

  Members.fromJson(Map<String, dynamic> json) {
    chatId = json['chat_id'];
    userId = json['user_id'];
    announcementId = json['announcement_id'];
    createdAt = json['createdAt'];
    user = json['user'] != null ? User.fromJson(json['user']) : null;
    post = json['post'] != null ? Post.fromJson(json['post']) : null;
    message =
    json['message'] != null ? Message.fromJson(json['message']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['chat_id'] = chatId;
    data['user_id'] = userId;
    data['announcement_id'] = announcementId;
    data['createdAt'] = createdAt;
    if (this.user != null) {
      data['user'] = user!.toJson();
    }
    if (this.post != null) {
      data['post'] = post!.toJson();
    }
    if (this.message != null) {
      data['message'] = message!.toJson();
    }
    return data;
  }
}

class User {
  String? avatar;
  String? fullName;
  String? userId;

  User({this.avatar, this.fullName, this.userId});

  User.fromJson(Map<String, dynamic> json) {
    avatar = json['avatar'];
    fullName = json['full_name'];
    userId = json['user_id'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['avatar'] = avatar;
    data['full_name'] = fullName;
    data['user_id'] = userId;
    return data;
  }
}

class Post {
  String? title;
  String? announcementId;
  String? slug;

  Post({this.title, this.announcementId, this.slug});

  Post.fromJson(Map<String, dynamic> json) {
    title = json['title'];
    announcementId = json['announcement_id'];
    slug = json['slug'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['title'] = title;
    data['announcement_id'] = announcementId;
    data['slug'] = slug;
    return data;
  }
}

class Message {
  String? messageId;
  String? senderId;
  String? content;
  bool? read;
  String? timestamp;
  String? createdAt;
  String? updatedAt;
  String? chatId;
  Null chatChatId;

  Message(
      {this.messageId,
        this.senderId,
        this.content,
        this.read,
        this.timestamp,
        this.createdAt,
        this.updatedAt,
        this.chatId,
        this.chatChatId});

  Message.fromJson(Map<String, dynamic> json) {
    messageId = json['message_id'];
    senderId = json['sender_id'];
    content = json['content'];
    read = json['read'];
    timestamp = json['timestamp'];
    createdAt = json['createdAt'];
    updatedAt = json['updatedAt'];
    chatId = json['chat_id'];
    chatChatId = json['chatChatId'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['message_id'] = messageId;
    data['sender_id'] = senderId;
    data['content'] = content;
    data['read'] = read;
    data['timestamp'] = timestamp;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    data['chat_id'] = chatId;
    data['chatChatId'] = chatChatId;
    return data;
  }
}
