class Autogenerated {
  bool? ok;
  List<MessagesList>? messages;

  Autogenerated({this.ok, this.messages});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    ok = json['ok'];
    if (json['messages'] != null) {
      messages = <MessagesList>[];
      json['messages'].forEach((v) {
        messages!.add(MessagesList.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['ok'] = ok;
    if (messages != null) {
      data['messages'] = messages!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class MessagesList {
  String? messageId;
  String? senderId;
  String? content;
  bool? read;
  String? timestamp;
  String? createdAt;
  String? updatedAt;
  String? chatId;

  MessagesList(
      {this.messageId,
        this.senderId,
        this.content,
        this.read,
        this.timestamp,
        this.createdAt,
        this.updatedAt,
        this.chatId,});

  MessagesList.fromJson(Map<String, dynamic> json) {
    messageId = json['message_id'];
    senderId = json['sender_id'];
    content = json['content'];
    read = json['read'];
    timestamp = json['timestamp'];
    createdAt = json['createdAt'];
    updatedAt = json['updatedAt'];
    chatId = json['chat_id'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['message_id'] = messageId;
    data['sender_id'] = senderId;
    data['content'] = content;
    data['read'] = read;
    data['timestamp'] = timestamp;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    data['chat_id'] = chatId;
    return data;
  }
}
